python3.13 extend.py data/optimize/config/sol-6d-c2-obj1.csv > output/sol-6d-c2-obj1.csv &
python3.13 extend.py data/optimize/config/SS-B.csv > output/SS-B.csv &
python3.13 extend.py data/optimize/config/SS-T.csv > output/SS-T.csv &
python3.13 extend.py data/optimize/config/wc+wc-3d-c4-obj1.csv > output/wc+wc-3d-c4-obj1.csv &
python3.13 extend.py data/optimize/config/SS-S.csv > output/SS-S.csv &
python3.13 extend.py data/optimize/config/SS-P.csv > output/SS-P.csv &
python3.13 extend.py data/optimize/config/SS-V.csv > output/SS-V.csv &
python3.13 extend.py data/optimize/config/SS-U.csv > output/SS-U.csv &
python3.13 extend.py data/optimize/config/wc+sol-3d-c4-obj1.csv > output/wc+sol-3d-c4-obj1.csv &
python3.13 extend.py data/optimize/config/SS-J.csv > output/SS-J.csv &
python3.13 extend.py data/optimize/config/SS-D.csv > output/SS-D.csv &
python3.13 extend.py data/optimize/config/SS-H.csv > output/SS-H.csv &
python3.13 extend.py data/optimize/config/SS-F.csv > output/SS-F.csv &
python3.13 extend.py data/optimize/config/SS-I.csv > output/SS-I.csv &
python3.13 extend.py data/optimize/config/X264_AllMeasurements.csv > output/X264_AllMeasurements.csv &
python3.13 extend.py data/optimize/config/SS-Q.csv > output/SS-Q.csv &
python3.13 extend.py data/optimize/config/SS-N.csv > output/SS-N.csv &
python3.13 extend.py data/optimize/config/SS-O.csv > output/SS-O.csv &
python3.13 extend.py data/optimize/config/rs-6d-c3_obj2.csv > output/rs-6d-c3_obj2.csv &
python3.13 extend.py data/optimize/config/SS-K.csv > output/SS-K.csv &
python3.13 extend.py data/optimize/config/Apache_AllMeasurements.csv > output/Apache_AllMeasurements.csv &
python3.13 extend.py data/optimize/config/SS-R.csv > output/SS-R.csv &
python3.13 extend.py data/optimize/config/SS-M.csv > output/SS-M.csv &
python3.13 extend.py data/optimize/config/SS-E.csv > output/SS-E.csv &
python3.13 extend.py data/optimize/config/SS-W.csv > output/SS-W.csv &
python3.13 extend.py data/optimize/config/SS-X.csv > output/SS-X.csv &
python3.13 extend.py data/optimize/config/wc+rs-3d-c4-obj1.csv > output/wc+rs-3d-c4-obj1.csv &
python3.13 extend.py data/optimize/config/HSMGP_num.csv > output/HSMGP_num.csv &
python3.13 extend.py data/optimize/config/SS-L.csv > output/SS-L.csv &
python3.13 extend.py data/optimize/config/SQL_AllMeasurements.csv > output/SQL_AllMeasurements.csv &
python3.13 extend.py data/optimize/config/SS-A.csv > output/SS-A.csv &
python3.13 extend.py data/optimize/config/SS-C.csv > output/SS-C.csv &
python3.13 extend.py data/optimize/config/SS-G.csv > output/SS-G.csv &
python3.13 extend.py data/optimize/config/wc-6d-c1-obj1.csv > output/wc-6d-c1-obj1.csv &
python3.13 extend.py data/optimize/config/rs-6d-c3_obj1.csv > output/rs-6d-c3_obj1.csv &
python3.13 extend.py data/optimize/binary_config/Scrum100k.csv > output/Scrum100k.csv &
python3.13 extend.py data/optimize/binary_config/FFM-1000-200-0.50-SAT-1.csv > output/FFM-1000-200-0.50-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/FM-500-100-0.75-SAT-1.csv > output/FM-500-100-0.75-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/FM-500-100-0.25-SAT-1.csv > output/FM-500-100-0.25-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/FFM-500-100-0.50-SAT-1.csv > output/FFM-500-100-0.50-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/FFM-250-50-0.50-SAT-1.csv > output/FFM-250-50-0.50-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/billing10k.csv > output/billing10k.csv &
python3.13 extend.py data/optimize/binary_config/FFM-125-25-0.50-SAT-1.csv > output/FFM-125-25-0.50-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/FM-500-100-1.00-SAT-1.csv > output/FM-500-100-1.00-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/FM-500-100-0.50-SAT-1.csv > output/FM-500-100-0.50-SAT-1.csv &
python3.13 extend.py data/optimize/binary_config/Scrum10k.csv > output/Scrum10k.csv &
python3.13 extend.py data/optimize/binary_config/Scrum1k.csv > output/Scrum1k.csv &
python3.13 extend.py data/optimize/hpo/healthCloseIsses12mths0011-easy.csv > output/healthCloseIsses12mths0011-easy.csv &
python3.13 extend.py data/optimize/hpo/healthCloseIsses12mths0001-hard.csv > output/healthCloseIsses12mths0001-hard.csv &
python3.13 extend.py data/optimize/misc/auto93.csv > output/auto93.csv &
python3.13 extend.py data/optimize/misc/Wine_quality.csv > output/Wine_quality.csv &
python3.13 extend.py data/optimize/process/pom3c.csv > output/pom3c.csv &
python3.13 extend.py data/optimize/process/coc1000.csv > output/coc1000.csv &
python3.13 extend.py data/optimize/process/xomo_ground.csv > output/xomo_ground.csv &
python3.13 extend.py data/optimize/process/xomo_osp2.csv > output/xomo_osp2.csv &
python3.13 extend.py data/optimize/process/pom3d.csv > output/pom3d.csv &
python3.13 extend.py data/optimize/process/xomo_osp.csv > output/xomo_osp.csv &
python3.13 extend.py data/optimize/process/pom3a.csv > output/pom3a.csv &
python3.13 extend.py data/optimize/process/pom3b.csv > output/pom3b.csv &
python3.13 extend.py data/optimize/process/nasa93dem.csv > output/nasa93dem.csv &
python3.13 extend.py data/optimize/process/xomo_flight.csv > output/xomo_flight.csv & 