mv output_lowX/SS-T.csv output_highX &
mv output_lowX/SS-P.csv output_highX &
mv output_lowX/SS-V.csv output_highX &
mv output_lowX/SS-U.csv output_highX &
mv output_lowX/X264_AllMeasurements.csv output_highX &
mv output_lowX/SS-Q.csv output_highX &
mv output_lowX/SS-N.csv output_highX &
mv output_lowX/SS-O.csv output_highX &
mv output_lowX/Apache_AllMeasurements.csv output_highX &
mv output_lowX/SS-R.csv output_highX &
mv output_lowX/SS-M.csv output_highX &
mv output_lowX/SS-W.csv output_highX &
mv output_lowX/SS-X.csv output_highX &
mv output_lowX/HSMGP_num.csv output_highX &
mv output_lowX/SS-L.csv output_highX &
mv output_lowX/SQL_AllMeasurements.csv output_highX &
mv output_lowX/FFM-250-50-0.50-SAT-1.csv output_highX &
mv output_lowX/billing10k.csv output_highX &
mv output_lowX/FFM-125-25-0.50-SAT-1.csv output_highX &
mv output_lowX/FM-500-100-1.00-SAT-1.csv output_highX &
mv output_lowX/Scrum10k.csv output_highX &
mv output_lowX/Scrum1k.csv output_highX &
mv output_lowX/Wine_quality.csv output_highX &
mv output_lowX/pom3c.csv output_highX &
mv output_lowX/coc1000.csv output_highX &
mv output_lowX/xomo_ground.csv output_highX &
mv output_lowX/xomo_osp2.csv output_highX &
mv output_lowX/pom3d.csv output_highX &
mv output_lowX/xomo_osp.csv output_highX &
mv output_lowX/pom3a.csv output_highX &
mv output_lowX/pom3b.csv output_highX &
mv output_lowX/nasa93dem.csv output_highX &
mv output_lowX/xomo_flight.csv output_highX &