python kmeans.py data/optimize/hpo/healthCloseIsses12mths0001-hard.csv > warm_start_outputs/healthCloseIsses12mths0001-hard.csv &
python kmeans.py data/optimize/hpo/healthCloseIsses12mths0011-easy.csv > warm_start_outputs/healthCloseIsses12mths0011-easy.csv &
python kmeans.py data/optimize/config/SS-B.csv > warm_start_outputs/SS-B.csv &
python kmeans.py data/optimize/config/sol-6d-c2-obj1.csv > warm_start_outputs/sol-6d-c2-obj1.csv &
python kmeans.py data/optimize/config/SS-L.csv > warm_start_outputs/SS-L.csv &
python kmeans.py data/optimize/config/SQL_AllMeasurements.csv > warm_start_outputs/SQL_AllMeasurements.csv &
python kmeans.py data/optimize/config/SS-D.csv > warm_start_outputs/SS-D.csv &
python kmeans.py data/optimize/config/SS-I.csv > warm_start_outputs/SS-I.csv &
python kmeans.py data/optimize/config/SS-G.csv > warm_start_outputs/SS-G.csv &
python kmeans.py data/optimize/config/SS-S.csv > warm_start_outputs/SS-S.csv &
python kmeans.py data/optimize/config/SS-E.csv > warm_start_outputs/SS-E.csv &
python kmeans.py data/optimize/config/SS-O.csv > warm_start_outputs/SS-O.csv &
python kmeans.py data/optimize/config/wc-6d-c1-obj1.csv > warm_start_outputs/wc-6d-c1-obj1.csv &
python kmeans.py data/optimize/config/SS-A.csv > warm_start_outputs/SS-A.csv &
python kmeans.py data/optimize/config/SS-X.csv > warm_start_outputs/SS-X.csv &
python kmeans.py data/optimize/config/SS-V.csv > warm_start_outputs/SS-V.csv &
python kmeans.py data/optimize/config/SS-Q.csv > warm_start_outputs/SS-Q.csv &
python kmeans.py data/optimize/config/SS-C.csv > warm_start_outputs/SS-C.csv &
python kmeans.py data/optimize/config/rs-6d-c3_obj1.csv > warm_start_outputs/rs-6d-c3_obj1.csv &
python kmeans.py data/optimize/config/SS-T.csv > warm_start_outputs/SS-T.csv &
python kmeans.py data/optimize/config/rs-6d-c3_obj2.csv > warm_start_outputs/rs-6d-c3_obj2.csv &
python kmeans.py data/optimize/config/SS-R.csv > warm_start_outputs/SS-R.csv &
python kmeans.py data/optimize/config/SS-N.csv > warm_start_outputs/SS-N.csv &
python kmeans.py data/optimize/config/wc+rs-3d-c4-obj1.csv > warm_start_outputs/wc+rs-3d-c4-obj1.csv &
python kmeans.py data/optimize/config/SS-K.csv > warm_start_outputs/SS-K.csv &
python kmeans.py data/optimize/config/wc+wc-3d-c4-obj1.csv > warm_start_outputs/wc+wc-3d-c4-obj1.csv &
python kmeans.py data/optimize/config/SS-F.csv > warm_start_outputs/SS-F.csv &
python kmeans.py data/optimize/config/SS-J.csv > warm_start_outputs/SS-J.csv &
python kmeans.py data/optimize/config/X264_AllMeasurements.csv > warm_start_outputs/X264_AllMeasurements.csv &
python kmeans.py data/optimize/config/SS-H.csv > warm_start_outputs/SS-H.csv &
python kmeans.py data/optimize/config/SS-P.csv > warm_start_outputs/SS-P.csv &
python kmeans.py data/optimize/config/HSMGP_num.csv > warm_start_outputs/HSMGP_num.csv &
python kmeans.py data/optimize/config/Apache_AllMeasurements.csv > warm_start_outputs/Apache_AllMeasurements.csv &
python kmeans.py data/optimize/config/SS-U.csv > warm_start_outputs/SS-U.csv &
python kmeans.py data/optimize/config/wc+sol-3d-c4-obj1.csv > warm_start_outputs/wc+sol-3d-c4-obj1.csv &
python kmeans.py data/optimize/config/SS-W.csv > warm_start_outputs/SS-W.csv &
python kmeans.py data/optimize/config/SS-M.csv > warm_start_outputs/SS-M.csv &
python kmeans.py data/optimize/process/pom3c.csv > warm_start_outputs/pom3c.csv &
python kmeans.py data/optimize/process/pom3a.csv > warm_start_outputs/pom3a.csv &
python kmeans.py data/optimize/process/xomo_ground.csv > warm_start_outputs/xomo_ground.csv &
python kmeans.py data/optimize/process/nasa93dem.csv > warm_start_outputs/nasa93dem.csv &
python kmeans.py data/optimize/process/xomo_flight.csv > warm_start_outputs/xomo_flight.csv &
python kmeans.py data/optimize/process/xomo_osp.csv > warm_start_outputs/xomo_osp.csv &
python kmeans.py data/optimize/process/pom3b.csv > warm_start_outputs/pom3b.csv &
python kmeans.py data/optimize/process/pom3d.csv > warm_start_outputs/pom3d.csv &
python kmeans.py data/optimize/process/xomo_osp2.csv > warm_start_outputs/xomo_osp2.csv &
python kmeans.py data/optimize/process/coc1000.csv > warm_start_outputs/coc1000.csv &
python kmeans.py data/optimize/binary_config/FFM-250-50-0.50-SAT-1.csv > warm_start_outputs/FFM-250-50-0.50-SAT-1.csv &
python kmeans.py data/optimize/binary_config/Scrum1k.csv > warm_start_outputs/Scrum1k.csv &
python kmeans.py data/optimize/binary_config/billing10k.csv > warm_start_outputs/billing10k.csv &
python kmeans.py data/optimize/binary_config/Scrum10k.csv > warm_start_outputs/Scrum10k.csv &
python kmeans.py data/optimize/binary_config/FM-500-100-0.25-SAT-1.csv > warm_start_outputs/FM-500-100-0.25-SAT-1.csv &
python kmeans.py data/optimize/binary_config/FM-500-100-0.50-SAT-1.csv > warm_start_outputs/FM-500-100-0.50-SAT-1.csv &
python kmeans.py data/optimize/binary_config/FFM-1000-200-0.50-SAT-1.csv > warm_start_outputs/FFM-1000-200-0.50-SAT-1.csv &
python kmeans.py data/optimize/binary_config/FFM-125-25-0.50-SAT-1.csv > warm_start_outputs/FFM-125-25-0.50-SAT-1.csv &
python kmeans.py data/optimize/binary_config/FM-500-100-1.00-SAT-1.csv > warm_start_outputs/FM-500-100-1.00-SAT-1.csv &
python kmeans.py data/optimize/binary_config/FFM-500-100-0.50-SAT-1.csv > warm_start_outputs/FFM-500-100-0.50-SAT-1.csv &
python kmeans.py data/optimize/binary_config/FM-500-100-0.75-SAT-1.csv > warm_start_outputs/FM-500-100-0.75-SAT-1.csv &
python kmeans.py data/optimize/binary_config/Scrum100k.csv > warm_start_outputs/Scrum100k.csv &
python kmeans.py data/optimize/misc/Wine_quality.csv > warm_start_outputs/Wine_quality.csv &
python kmeans.py data/optimize/misc/auto93.csv > warm_start_outputs/auto93.csv &